Resources:
  Bucket:
    Type: AWS::S3::Bucket

  Queue:
    Type: AWS::SQS::Queue

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S

  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/network-demo/bucket"
      Type: String
      Value: !Ref Bucket

  QueueUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/network-demo/queue"
      Type: String
      Value: !Ref Queue

  TableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/network-demo/table"
      Type: String
      Value: !Ref Table
